# coding=utf-8
import setuptools

setuptools.setup(name='districtgenerator',
                 version='0.0.1',
                 description='Energy profile generation and '
                             'optimization of districts',
                 url='https://github.com/RWTH-EBC/districtgenerator',
                 author='Sarah Henn',
                 author_email='shenn@eonerc.rwth-aachen.de',
                 license='MIT License',
                 packages=setuptools.find_packages(),

                 data_files=[
                     ('districtgenerator/data/weather',
                      ['districtgenerator/data/weather/TRY2015_Zone0_kalt.txt',
                       'districtgenerator/data/weather/TRY2015_Zone0_normal.txt',
                       'districtgenerator/data/weather/TRY2015_Zone0_warm.txt',
                       'districtgenerator/data/weather/TRY2015_Zone1_kalt.txt',
                       'districtgenerator/data/weather/TRY2015_Zone1_normal.txt',
                       'districtgenerator/data/weather/TRY2015_Zone1_warm.txt',
                       'districtgenerator/data/weather/TRY2015_Zone2_kalt.txt',
                       'districtgenerator/data/weather/TRY2015_Zone2_normal.txt',
                       'districtgenerator/data/weather/TRY2015_Zone2_warm.txt',
                       'districtgenerator/data/weather/TRY2015_Zone3_kalt.txt',
                       'districtgenerator/data/weather/TRY2015_Zone3_normal.txt',
                       'districtgenerator/data/weather/TRY2015_Zone3_warm.txt',
                       'districtgenerator/data/weather/TRY2015_Zone4_kalt.txt',
                       'districtgenerator/data/weather/TRY2015_Zone4_normal.txt',
                       'districtgenerator/data/weather/TRY2015_Zone4_warm.txt',
                       'districtgenerator/data/weather/TRY2015_Zone5_kalt.txt',
                       'districtgenerator/data/weather/TRY2015_Zone5_normal.txt',
                       'districtgenerator/data/weather/TRY2015_Zone5_warm.txt',
                       'districtgenerator/data/weather/TRY2015_Zone6_kalt.txt',
                       'districtgenerator/data/weather/TRY2015_Zone6_normal.txt',
                       'districtgenerator/data/weather/TRY2015_Zone6_warm.txt', ]
                      ),
                     ('districtgenerator/data/wind_turbine_models',
                      ['districtgenerator/data/wind_turbine_models/WT_Enercon_E40.csv'],
                      ),
                     ('districtgenerator/data',
                      ['districtgenerator/data/central_device_data.json',
                       'districtgenerator/data/decentral_device_data.json',
                       'districtgenerator/data/design_building_data.json',
                       'districtgenerator/data/design_weather_data.json',
                       'districtgenerator/data/eco_data.json',
                       'districtgenerator/data/gurobi_settings.json',
                       'districtgenerator/data/heat_grid.json',
                       'districtgenerator/data/model_parameters_EHDO.json',
                       'districtgenerator/data/physics_data.json',
                       'districtgenerator/data/site_data.json',
                       'districtgenerator/data/technical_parameters_EHDO.json',
                       'districtgenerator/data/time_data.json',
                       'districtgenerator/data/dhw_stochastical.xlsx']

                      ),
                 ],

                 install_requires=['numpy', 'pandas', 'matplotlib', 'scipy',
                                   'teaser', 'richardsonpy', 'pylightxl', 'gurobipy'],
                 classifiers=["Programming Language :: Python :: 3"],
                 )
