# -*- coding: utf-8 -*-
"""
Contracting Business Model / Wärmecontracting (BM 2)

Ownership
---------
- Energy hub: operator
- District heating network: operator
- Decentralized PV: end customer
- Public electricity grid: DSO

Electricity logic
-----------------
- No local electricity sales by the operator to buildings
- Electricity generated by the energy hub is exported to the public grid
- End customers cover residual electricity demand individually via the public grid
- Decentralized PV remains on the customer side

Post-processing logic
---------------------
- p_min is the cost-covering offered heat price of the model.
  It is derived from the discounted net system cost of the operator.
- p_max is derived from the end-customer NPV indifference condition
  against the reference case.
- The class provides model-specific NPV quantities and scenario results,
  but it does not make the final feasibility decision of the overall run.
"""

from typing import Dict, Optional

from .Basis import BusinessModelBase


class WaermecontractingBM(BusinessModelBase):

    def get_price_el_revenue_by_year(self) -> dict:
        """No local electricity sales by the operator in the contracting model."""
        return {year: 0.0 for year in self.interpolation_points}

    def calculate_kpis(self, kpis, data, result: dict) -> None:
        """
        Calculate model-specific KPIs for the contracting business model.

        Implemented here:
        - cost-covering heat price p_min from operator-side net system costs
        - maximum acceptable heat price p_max from end-customer NPV equality
        - scenario-specific helper outputs for the run logic

        Not implemented here:
        - final feasibility decision of the overall workflow
        - iterative exclusion / re-run control
        """
        support_years = list(self.interpolation_points)
        if not support_years:
            kpis.p_min = None
            kpis.p_max = None
            return

        tac_total = float(result["tac"])
        bw_tac_total = self._bw_constant_annual(tac_total)

        heat_total = self._heat_delivered_total(data)
        heat_by_building = self._heat_delivered_by_building(data)
        bw_heat_total = self._bw_constant_annual(heat_total)

        # B2 TAC reconciliation:
        # remove design supply_costs_el (Endkunde + EH zu p_eh_static)
        # add operational EH electricity cost (dynamic profile if enabled)
        bw_supply_el_design = self._bw_supply_costs_el_design_static(result)
        bw_eh_el_operational = self._bw_grid_cost_operational(
            data=data, support_years=support_years, scope="eh")
        bw_tac_corrected = (
                bw_tac_total
                - bw_supply_el_design
                + bw_eh_el_operational
        )
        p_min = bw_tac_corrected / bw_heat_total if bw_heat_total > 0 else None

        npv_ref_by_building = self.ecoData.get("npv_ref_by_building", {})
        scenario = self.ecoData.get("scenario", "B")

        npv_strom_wn_by_building = self._npv_strom_wn_by_building(
            data=data,
            result=result,
            kpis=kpis,
        )
        npv_wn_at_p_min_by_building = self._npv_wn_by_building_at_price(
            heat_by_building=heat_by_building,
            npv_strom_wn_by_building=npv_strom_wn_by_building,
            heat_price=p_min,
        )

        scenario_a = self._scenario_a(
            heat_by_building=heat_by_building,
            npv_ref_by_building=npv_ref_by_building,
            npv_strom_wn_by_building=npv_strom_wn_by_building,
            npv_wn_at_price_by_building=npv_wn_at_p_min_by_building,
        )
        scenario_b = self._scenario_b(
            heat_by_building=heat_by_building,
            npv_ref_by_building=npv_ref_by_building,
            npv_strom_wn_by_building=npv_strom_wn_by_building,
            npv_wn_at_price_by_building=npv_wn_at_p_min_by_building,
        )

        p_max = scenario_a["p_max"] if scenario == "A" else scenario_b["p_max"]

        kpis.p_min = p_min
        kpis.p_max = p_max
        kpis.business_model = self.ecoData.get("business_model")
        kpis.waermecontracting_breakdown = {
            "tac_total": tac_total,
            "bw_tac_total": bw_tac_total,
            "heat_total_kWh": heat_total,
            "bw_heat_total": bw_heat_total,
            "bw_supply_el_design": bw_supply_el_design,
            "bw_eh_el_operational": bw_eh_el_operational,
            "bw_tac_corrected": bw_tac_corrected,
            "p_min": p_min,
            "p_max": p_max,
            "p_max_a": scenario_a["p_max"],
            "p_max_b": scenario_b["p_max"],
            "scenario": scenario,
            "npv_strom_wn_by_building": npv_strom_wn_by_building,
            "npv_wn_at_p_min_by_building": npv_wn_at_p_min_by_building,
            "scenario_a": scenario_a,
            "scenario_b": scenario_b,
        }
        # Waermecontracting:
        kpis.bm_breakdown = kpis.waermecontracting_breakdown

    def _npv_strom_wn_by_building(self, data, result: dict, kpis=None) -> Dict[int, float]:
        """
        Building-level electricity-side NPV in the WN case.

        Contracting-specific assumptions:
        - decentralized PV remains with the end customer
        - no local electricity sales by the operator to buildings
        - customer electricity NPV therefore consists of:
          - annualized PV cost (customer side)
          - grid procurement cost
          - PV feed-in revenue
        """
        pv_flows_by_building_year = self._pv_flows_by_building_year(data, result)
        support_years = sorted(pv_flows_by_building_year.keys())

        bw_feed_in_by_building = self._bw_pv_feed_in_by_building(
            data=data,
            pv_flows_by_building_year=pv_flows_by_building_year,
        )
        bw_grid_cost_by_building = self._bw_grid_cost_by_building(
            data=data,
            result=result,
            support_years=support_years,
        )
        dev_costs_all = self._require_decentral_costs(kpis)

        npv_by_building = {}

        for n in range(len(data.district)):
            heater = data.district[n]["buildingFeatures"].get("heater", "").upper()
            if heater != "HEAT_GRID":
                continue

            pv_cost_ann = 0.0
            dev_costs = dev_costs_all.get(n, {})
            if "PV" in dev_costs:
                pv_cost_ann = float(dev_costs["PV"].get("subsidized_annual_cost", 0.0))

            bw_pv_cost = self._bw_constant_annual(pv_cost_ann)
            bw_grid_cost = bw_grid_cost_by_building.get(n, 0.0)
            bw_feed_in_revenue = bw_feed_in_by_building.get(n, 0.0)

            npv_by_building[n] = -bw_pv_cost - bw_grid_cost + bw_feed_in_revenue

        return npv_by_building

    def _npv_wn_by_building_at_price(
        self,
        heat_by_building: Dict[int, float],
        npv_strom_wn_by_building: Dict[int, float],
        heat_price: Optional[float],
    ) -> Dict[int, float]:
        """
        Total end-customer NPV in the WN case for a given heat price.

        NPV_wn,i(p) = - q_i * p * PVAF + npv_strom_wn_i
        """
        if heat_price is None:
            return {}

        pvaf = self._present_value_factor()
        npv_by_building = {}

        for n, heat_kwh in heat_by_building.items():
            npv_heat = -heat_kwh * heat_price * pvaf
            npv_strom = npv_strom_wn_by_building.get(n, 0.0)
            npv_by_building[n] = npv_heat + npv_strom

        return npv_by_building

    def _scenario_a(
        self,
        heat_by_building: Dict[int, float],
        npv_ref_by_building: Dict[int, float],
        npv_strom_wn_by_building: Dict[int, float],
        npv_wn_at_price_by_building: Dict[int, float],
    ) -> dict:
        """
        Scenario A: no mandatory connection.

        The class only prepares building-level results.
        The final exclusion, re-run, and feasibility decision are handled outside.
        """
        if not npv_ref_by_building:
            return {
                "connected": list(heat_by_building.keys()),
                "excluded": [],
                "needs_iteration": False,
                "p_max": None,
                "p_max_by_building": {},
                "building_details": {},
            }

        connected = []
        excluded = []
        p_max_by_building = {}
        building_details = {}

        for n, heat_kwh in heat_by_building.items():
            npv_ref = npv_ref_by_building.get(n, 0.0)
            npv_wn_at_price = npv_wn_at_price_by_building.get(n, 0.0)
            npv_strom_wn = npv_strom_wn_by_building.get(n, 0.0)

            p_max_i = self._p_max_from_npvs(
                heat_kwh=heat_kwh,
                npv_ref=npv_ref,
                npv_wn_other=npv_strom_wn,
            )
            p_max_by_building[n] = p_max_i

            is_economic_at_price = (
                    p_max_i is not None
                    and npv_wn_at_price >= npv_ref)
            if is_economic_at_price:
                connected.append(n)
            else:
                excluded.append(n)

            building_details[n] = {
                "heat_kWh": heat_kwh,
                "npv_ref": npv_ref,
                "npv_strom_wn": npv_strom_wn,
                "npv_wn_at_price": npv_wn_at_price,
                "economic_at_price": is_economic_at_price,
                "p_max": p_max_i,
            }

        # PDF Bewertungslogik Szenario A:
        # "Für die verbleibenden Gebäude wird jeweils ein p_max,i berechnet.
        #  p_max = min_i(p_max,i)"
        # -> nur die nicht ausgeschlossenen Gebäude gehen in das min ein.
        valid_p_max = [
            p_max_by_building[n]
            for n in connected
            if p_max_by_building.get(n) is not None
        ]
        p_max = min(valid_p_max) if valid_p_max else None

        return {
            "connected": connected,
            "excluded": excluded,
            "needs_iteration": len(excluded) > 0,
            "p_max": p_max,
            "p_max_by_building": p_max_by_building,
            "building_details": building_details,
        }

    def _scenario_b(
        self,
        heat_by_building: Dict[int, float],
        npv_ref_by_building: Dict[int, float],
        npv_strom_wn_by_building: Dict[int, float],
        npv_wn_at_price_by_building: Dict[int, float],
    ) -> dict:
        """
        Scenario B: mandatory connection.

        The class provides the aggregate NPV quantities needed by the outer run logic.
        """
        if not npv_ref_by_building:
            return {
                "sum_npv_wn_at_price": 0.0,
                "sum_npv_ref": 0.0,
                "p_max": None,
                "connected_buildings": list(heat_by_building.keys()),
            }

        sum_npv_ref = 0.0
        sum_npv_wn_at_price = 0.0
        sum_npv_strom_wn = 0.0
        heat_total = 0.0

        for n, heat_kwh in heat_by_building.items():
            sum_npv_ref += npv_ref_by_building.get(n, 0.0)
            sum_npv_wn_at_price += npv_wn_at_price_by_building.get(n, 0.0)
            sum_npv_strom_wn += npv_strom_wn_by_building.get(n, 0.0)
            heat_total += heat_kwh

        p_max = self._p_max_from_npvs(
            heat_kwh=heat_total,
            npv_ref=sum_npv_ref,
            npv_wn_other=sum_npv_strom_wn,
        ) if heat_total > 0 else None

        return {
            "sum_npv_wn_at_price": sum_npv_wn_at_price,
            "sum_npv_ref": sum_npv_ref,
            "sum_npv_strom_wn": sum_npv_strom_wn,
            "heat_total_kWh": heat_total,
            "p_max": p_max,
            "connected_buildings": list(heat_by_building.keys()),
        }